name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      # Server deployment
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install server dependencies
        run: npm ci --production
        working-directory: ./server
      
      - name: Build server
        run: npm run build
        working-directory: ./server
      
      # Client deployment
      - name: Install client dependencies
        run: npm ci
        working-directory: ./client
      
      - name: Build client
        run: npm run build
        working-directory: ./client
      
      # Add your Windows-specific deployment commands here
      # For example, if deploying to Azure App Service:
      - name: 'Deploy to Azure Web App'
        if: success()
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'your-app-name'
          slot-name: 'Production'
          # publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./client/build