name: Client CI

on:
  push:
    branches: [develop, feature/*]
    paths: ['client/**']
  pull_request:
    branches: [develop]
    paths: ['client/**']

jobs:
  test:
    runs-on: windows-latest  # Changed to Windows runner
    defaults:
      run:
        shell: pwsh  # Use PowerShell Core
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        working-directory: ./client
        env:
          CI: true
          
      - name: Run tests
        run: npm test
        working-directory: ./client
        env:
          CI: true

  build:
    needs: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install and build
        run: |
          npm ci
          npm run build
        working-directory: ./client
        env:
          CI: true
          
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: client/build