name: Server CI

on:
  push:
    branches: [develop, feature/*]
    paths: ['server/**']
  pull_request:
    branches: [develop]
    paths: ['server/**']

jobs:
  test:
    runs-on: windows-latest
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: --health-cmd "mongo --eval 'db.runCommand(\"ping\").ok'" --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        working-directory: ./server
        env:
          CI: true
          
      - name: Run tests
        run: npm test
        working-directory: ./server
        env:
          CI: true
          MONGO_URI: mongodb://localhost:27017/lms_test
          # JWT_SECRET: ${{ secrets.JWT_SECRET }}
          # STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}